server:
  port: 4399
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/network?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.nju.networktest.entity.po
  configuration:
    map-underscore-to-camel-case: true
